### ISSUE TITLE
Improve todo page

### ISSUE THREAD

**Issue by yegorgunko** [yegorgunko/hrtc-web#2]
- [ ] Add grouping by the due date

- [ ] Add expansion items

- [ ] Make list bigger and easier to read

- [ ] Add key elements highlighting with primary color
